### ISSUE TITLE
Power on with HDMI

### ISSUE THREAD

**Issue by robertvorthman** [bschlenk/homebridge-roku#1]
If you don't have an IR blaster, a Raspberry Pi can turn on a TV if connected with an HDMI cable using the HDMI-CEC protocol.  See https://github.com/jbree/homebridge-platform-cec

**Comment by bschlenk** [comment]
Thanks, I'll look into this. Do you know if CEC would allow the raspberry pi to turn the TV on without also switching the input over to the raspberry pi? I suppose a home button click could be sent after a delay, but that feels sort hacky.

**Comment by bschlenk** [comment]
Closing in favor of https://github.com/bschlenk/homebridge-roku/issues/4
