### ISSUE TITLE
UDID error when using 3.0.0 Alpha 1

### ISSUE THREAD

**Issue by ghost** [bschlenk/homebridge-roku#117]
![13B4040B-92B3-41FE-A178-7427A76BF175](https://user-images.githubusercontent.com/19377918/62496954-85e0c600-b7a8-11e9-816d-ef44fa33160f.png)

**Comment by visnaut** [comment]
I'm getting the same

**Comment by bschlenk** [comment]
Fixed in https://github.com/bschlenk/homebridge-roku/commit/c1c67ca833206671387c6d7fdb9536ff846e0c0f. Please update to v3.0.1.
