### ISSUE TITLE
Add iOS remote support

### ISSUE THREAD

**Issue by jcbshw** [bschlenk/homebridge-roku#136]
Currently running v3.0.0-alpha1 without any issues. Hopefully adding iOS remote support would be possible. The Homebridge Bravia plugin currently has this implemented and it allows me to control the volume as well.

**Comment by roberkane212** [comment]
@jcbshw you’ll have to use more than one instance if you want it to work on multiple TV’s

**Comment by jcbshw** [comment]
@roberkane212 thanks, I was wondering about this the other day since I noticed my Roku had a remote while my Bravias remote was missing

**Comment by roberkane212** [comment]
@jcbshw ok I’m glad u can help, if you are using raspberry pi or config ui x it should be easy. If you need help let me know
