### ISSUE TITLE
3.0.0-alpha with non-TV Rokus

### ISSUE THREAD

**Issue by radiocolin** [bschlenk/homebridge-roku#137]
The 3.0.0-alpha seems to work fine with non-TV Rokus (eg: Roku Ultra), but if you set the isTV parameter to "false", it errors on Homebridge startup with a UUID error.

**Comment by codyde** [comment]
I'm having this same issue. Any resolution yet?

**Comment by radiocolin** [comment]
I’ve just been using it with the “isTV” parameter set to true for my Roku Ultra and it works fine

**Comment by codyde** [comment]
> I’ve just been using it with the “isTV” parameter set to true for my Roku Ultra and it works fine

Thanks - this worked, I feel dumb for posting now :) haha

**Comment by segulls** [comment]
how do I change the parameter

**Comment by radiocolin** [comment]
In your Json config 

-CW
