### ISSUE TITLE
Having Trouble With control centre remote

### ISSUE THREAD

**Issue by yonigold1** [bschlenk/homebridge-roku#165]
im having trouble using the remote for my Roku TCL in the control centre there seems to be no way to exit a channel and no way to power it down and no way to switch between channels in the control centre remote. is there something i need to do for those buttons/controls to show?

![IMG_4967](https://user-images.githubusercontent.com/34217684/80651112-41d2d700-8a43-11ea-8182-50da31fb1356.PNG)
![IMG_4966](https://user-images.githubusercontent.com/34217684/80651113-426b6d80-8a43-11ea-84f6-a17c604b11af.PNG)

**Comment by Haglerd** [comment]
At least it’s showing for you I guess... for me it disappears after 30 seconds

**Comment by bschlenk** [comment]
I think that's just how it is... apple doesn't show any other buttons for homekit tv's. I'm thinking of maybe adding a config option to customize the behavior of the `i` button, then you could set it to `HOME` instead, which would make it a little easier to use. Do you think that would solve the problem?

**Comment by bschlenk** [comment]
Added support for [overriding the info button](https://github.com/bschlenk/homebridge-roku#infobuttonoverride). Hopefully that will make the remote more useable. Feel free to reopen if you think this can be done in a better way.

**Comment by yonigold1** [comment]
i couldn’t seem to get that to work either i changed the `i`button to home and it still works as the info button 
Are u perhaps able to do the same for the pause/play button ?

**Comment by yonigold1** [comment]
Yes and sure thing :) 
<img width="536" alt="SS 2020-06-11 at 6 03 20 PM" src="https://user-images.githubusercontent.com/34217684/84443816-64ddd280-ac0e-11ea-9201-9673ae9c424f.png">

Let me know if i did something wrong in the config.

**Comment by bschlenk** [comment]
Ah, there it is! `infoButtonOverride` should be one level higher in the config, same level as `ip`, `name`, etc.
