### ISSUE TITLE
Error Message -  additional copy of homebridge and hap-nodejs. 

### ISSUE THREAD

**Issue by Haglerd** [bschlenk/homebridge-roku#172]
The plugin "homebridge-roku" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

**Comment by roberkane212** [comment]
I’m having the same issue

**Comment by bschlenk** [comment]
Fixed in https://github.com/bschlenk/homebridge-roku/commit/5446afb8971f4cd4a148a1086f53333f692c60d8
