### ISSUE TITLE
Roku Volume

### ISSUE THREAD

**Issue by Haglerd** [bschlenk/homebridge-roku#174]
Maybe this is just a question and I don't know how, but is there a way to reduce the amount of increase and decrease in the volume buttons. I press it once and it sends the volume through the roof.

**Comment by bschlenk** [comment]
You can set `volumeIncrement` in your config. It used to default to 5, but in 3.0.1 it defaults to 1 since that makes more sense when using the phone’s volume buttons. https://github.com/bschlenk/homebridge-roku/blob/master/README.md#volumeincrement--volumedecrement

**Comment by Haglerd** [comment]
Perfect. Makes sense and I just noticed that when it does show up in the remote area it doesn't do the big jump anymore.
