### ISSUE TITLE
Can’t Change Name in Home App

### ISSUE THREAD

**Issue by Techman55** [bschlenk/homebridge-roku#221]
￼Can't change name of accessory in Home app. I'm using a Roku Ultra. 

When I try to change the name in the Home app, once I click away the name reverts to the old one. I've also tried changing the friendly name in the config and in the homebridge UI accessories tab; nothing seems to work.

Any help is appreciated, Thanks!

**Comment by DallasHoff** [comment]
Hi there. I was able to do it by changing the value of the "userDeviceName" field. Have you tried that?

**Comment by Techman55** [comment]
> Hi there. I was able to do it by changing the value of the "userDeviceName" field. Have you tried that?

Just tried that and it worked, thanks!
