### ISSUE TITLE
Suppress Update Tag for Beta Version

### ISSUE THREAD

**Issue by rweckhoff** [bschlenk/homebridge-roku#225]
I'm unable to get the 4.0.0 beta 1 to actually work.  Homebridge 1.3.1 w homebridge-config-ui-x v4.39.1 keep on advising that there is an upgrade.  Please suppress upgrade notifications for beta software.

**Comment by bschlenk** [comment]
Is it actually forcing you to upgrade? I don’t know anything about homebridge-config-ui-x, I don’t see anything about suppressing upgrade notifications in their documentation. You may want to open an issue in [their repo](https://github.com/oznu/homebridge-config-ui-x) instead, I agree it shouldn’t be advising you to upgrade to beta releases.

**Comment by rweckhoff** [comment]
> Is it actually forcing you to upgrade? I don’t know anything about homebridge-config-ui-x, I don’t see anything about suppressing upgrade notifications in their documentation. You may want to open an issue in [their repo](https://github.com/oznu/homebridge-config-ui-x) instead, I agree it shouldn’t be advising you to upgrade to beta releases.

Not forcing an upgrade.  Shows as update available.  I do not see other beta versions as "Plugin Out of Date".

<img width="1035" alt="Screen Shot 2021-03-02 at 15 27 07 PM" src="https://user-images.githubusercontent.com/61269490/109710796-1ab9ca00-7b6c-11eb-9d9e-51531833ab67.png">

**Comment by bschlenk** [comment]
Ah I see what happened, I published the beta as latest instead of next. Just published a new patch version setting latest back to 3.x. Does that make the ui stop suggesting an update?

**Comment by rweckhoff** [comment]
All good .... 3.0.2 = latest.  Thanks for the quick turnaround!
