### ISSUE TITLE
Help (or feature request?): Roku stick option to return to home screen

### ISSUE THREAD

**Issue by jfmach** [bschlenk/homebridge-roku#227]
Hello,

Thanks for the plugin it works great! I do have one question about the Roku sticks. I can choose a channel but I can't go back to the home screen. Is there a way to do that?

If not, is it possible to add a feature, either a "Home Screen" channel, or where turning the stick "off" sends it back to the home screen?
Thanks!

- Jeff

**Comment by bschlenk** [comment]
In the 4.0.0 beta version I’m pretty sure I added the home page as one of the inputs. In version 3 there’s an [infoButtonOverride](https://github.com/bschlenk/homebridge-roku#infobuttonoverride) config which you can use to override the behavior of the control center remote "i" button to "HOME"

**Comment by jfmach** [comment]
Thanks, I am trying the version 4 beta route but am running into an issue with the config. I've tried completely uninstalling and removing all references to the plugin in the config file in case v3 was interfering but no luck. After deploying v4 beta and saving the default config, I can't do anything. Upon restart of homebridge I see this in the log:

```
homebridge.log:[23/04/2021, 14:46:03] Loaded plugin: homebridge-roku@4.0.0-beta.2
homebridge.log:[23/04/2021, 14:46:03] Registering platform 'homebridge-roku.RokuPlatform'
homebridge.log:[23/04/2021, 14:46:04] No plugin was found for the platform "Roku Platform" in your config.json. Please make sure the corresponding plugin is installed correctly.
```

Are there extra instructions for the beta somewhere that I need to follow?
Thank you,

- Jeff

**Comment by NateUT99** [comment]
There is some info in this comment that should get you up and running with v4... basically you need to manually add the platform code into your config.json (the GUI configuration doesn't seem to be working yet).

https://github.com/bschlenk/homebridge-roku/issues/202#issuecomment-822540525

**Comment by NateUT99** [comment]
> Thanks, I am trying the version 4 beta route but am running into an issue with the config. I've tried completely uninstalling and removing all references to the plugin in the config file in case v3 was interfering but no luck. After deploying v4 beta and saving the default config, I can't do anything. Upon restart of homebridge I see this in the log:
> 
> ```
> homebridge.log:[23/04/2021, 14:46:03] Loaded plugin: homebridge-roku@4.0.0-beta.2
> homebridge.log:[23/04/2021, 14:46:03] Registering platform 'homebridge-roku.RokuPlatform'
> homebridge.log:[23/04/2021, 14:46:04] No plugin was found for the platform "Roku Platform" in your config.json. Please make sure the corresponding plugin is installed correctly.
> ```
> 
> Are there extra instructions for the beta somewhere that I need to follow?
> Thank you,
> 
> * Jeff


If you manually copy/paste the config in the comment linked below, v4 should work for you (you'll need to manually add the TV accessory via the Home app). The GUI configuration doesn't seem to be working quite yet for v4. Hope it helps! :)

https://github.com/bschlenk/homebridge-roku/issues/202#issuecomment-822540525

**Comment by jfmach** [comment]
Thanks @NateUT99  ! I was able to get the beta setup, and it discovered all my TVs and sticks beautifully.

I can return home with the "i" button on the Apple remote, however the "Home" menu option from inside Apple Homekit itself does not work, it says "No response" when trying to use it.
I am trying to setup a scene to turn off all TVs and set the sticks back to home from inside Homekit rather than using the Apple TV remote. Do you know if this is doable?

- Jeff

**Comment by NateUT99** [comment]
> Thanks @NateUT99 ! I was able to get the beta setup, and it discovered all my TVs and sticks beautifully.
> 
> I can return home with the "i" button on the Apple remote, however the "Home" menu option from inside Apple Homekit itself does not work, it says "No response" when trying to use it.
> I am trying to setup a scene to turn off all TVs and set the sticks back to home from inside Homekit rather than using the Apple TV remote. Do you know if this is doable?
> 
> * Jeff

Unfortunately I haven’t dug too deep into the plug-in, I’m mainly only use one input (appletv 4k) and to control on/off in automations, so I haven’t done anything with inputs.

**Comment by jfmach** [comment]
Thank you, I will open a specific issue for this.
