### ISSUE TITLE
Homebridge running but “no response” in HomeKit

### ISSUE THREAD

**Issue by krazyflipj** [bschlenk/homebridge-roku#64]
For some reason, I get "no response" after a couple of hours after installing. Homebridge is running fine but I still get no response. Restarting computer, Homebridge, deleting accessories folder, and persistent folder doesn't fix it. It works fine after uninstalling.

**Comment by bschlenk** [comment]
Do you mean "no response" from HomeKit on your phone? Do you have any logs you can provide?

**Comment by krazyflipj** [comment]
so i tried installing the alpha build and after some time i get a no response in home app again. Weird thing is nothing shows up in my logfile

**Comment by krazyflipj** [comment]
put tv on fast start mode and so far i'm not having issues as i described above. Will continue to monitor

**Comment by Mxdanger** [comment]
If the TV accessory says "no response" then that might mean it is fully turned off.

> put tv on fast start mode and so far i'm not having issues as i described above. Will continue to monitor

There, now you got it working. As long as you keep Fast Start Mode on, you shouldn't get any response errors.

**Comment by krazyflipj** [comment]
@Mxdanger do you have Fast Start Mode on your Roku?

**Comment by Mxdanger** [comment]
@krazyflipj Yes I do, [here](https://www.amazon.com/TCL-50S423-Smart-Certified-Refurbished/dp/B07N4FJ7S4/ref=sr_1_2?keywords=50S423&qid=1549682384&s=Electronics&sr=1-2)’s the tv I have.

**Comment by krazyflipj** [comment]
Closing for now as error only occurs when tv is not on fast startup mode
